# This file was generated by GoReleaser. DO NOT EDIT.
cask "tnotes" do
  version "0.1.13"

  on_macos do
    url "https://github.com/bluegreenhq/tnotes/releases/download/v#{version}/tnotes_#{version}_darwin_all.tar.gz",
        verified: "github.com/bluegreenhq/tnotes"
    sha256 "7d64571c9675c9bbf20904380e2e9f1788269bd1bf19ea3ca90a8da733014be3"
  end

  name "tnotes"
  desc "Terminal-based note-taking app"
  homepage "https://github.com/bluegreenhq/tnotes"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tnotes"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tnotes"]
    end
  end

  # No zap stanza required

end
