# This file was generated by GoReleaser. DO NOT EDIT.
cask "tnotes" do
  version "0.1.20"

  on_macos do
    url "https://github.com/bluegreenhq/tnotes/releases/download/v#{version}/tnotes_#{version}_darwin_all.tar.gz",
        verified: "github.com/bluegreenhq/tnotes"
    sha256 "66ed69d88fe5a21a2d253a088fa879ce75490d4f50f961ed47b961f8d178475d"
  end

  name "tnotes"
  desc "Terminal-based note-taking app"
  homepage "https://github.com/bluegreenhq/tnotes"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tnotes"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tnotes"]
    end
  end

  # No zap stanza required

end
